# Generated by Django 2.1.2 on 2019-01-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypageinfomation',
            old_name='apiprovider',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='joiningdate',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='userimage',
        ),
        migrations.RemoveField(
            model_name='mypageinfomation',
            name='votingcount',
        ),
    ]
