# Generated by Django 2.1.2 on 2019-01-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypageinfomation',
            name='joiningdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadcontents',
            name='publisheddate',
            field=models.DateTimeField(null=True),
        ),
    ]
