# Generated by Django 2.1.2 on 2019-02-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcontents',
            name='contents',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='uploadcontents',
            name='index',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='uploadcontents',
            name='intro',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='uploadcontents',
            name='reference',
            field=models.CharField(default=True, max_length=2000),
        ),
    ]
