# Generated by Django 2.1.5 on 2019-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reward_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]