# Generated by Django 2.1.3 on 2019-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0002_post_reward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aaa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='bbb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ccc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='replymentcount',
            field=models.IntegerField(null=True),
        ),
    ]
