# Generated by Django 2.1.2 on 2019-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0002_auto_20190116_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypageinfomation',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
