# Generated by Django 2.1.2 on 2019-01-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0002_auto_20190109_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypageinfomation',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='joiningdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='pwd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='userimage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mypageinfomation',
            name='votingcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
