# Generated by Django 2.1.3 on 2019-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0003_auto_20190212_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replymentcount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
