# Generated by Django 2.1.2 on 2019-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0003_auto_20190116_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcontents',
            name='bbb',
        ),
        migrations.AddField(
            model_name='uploadcontents',
            name='replymentcount',
            field=models.IntegerField(null=True),
        ),
    ]
