# Generated by Django 2.1.2 on 2019-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0003_auto_20190109_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsinfo',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='previewinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='previewinfo',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadcontents',
            name='downloadcount',
            field=models.IntegerField(null=True),
        ),
    ]
