# Generated by Django 2.1.2 on 2019-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0003_auto_20190116_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcontents',
            name='bbb',
        ),
        migrations.AddField(
            model_name='uploadcontents',
            name='replymentcount',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ccc',
            new_name='isdelete',
        ),
        migrations.RemoveField(
            model_name='contentsinfo',
            name='aaa',
        ),
        migrations.RemoveField(
            model_name='uploadcontents',
            name='totalpages',
        ),
        migrations.AddField(
            model_name='contentsinfo',
            name='filesize',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
