# Generated by Django 2.1.2 on 2019-01-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0003_post_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsinfo',
            name='ftpsavefilename',
        ),
    ]
