# Generated by Django 2.1.2 on 2019-01-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0004_auto_20190117_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='opinions',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('posts_id', models.IntegerField()),
                ('context', models.CharField(max_length=100)),
                ('fromuser', models.CharField(max_length=100)),
                ('writeruser', models.CharField(max_length=100)),
                ('aaa', models.CharField(blank=True, max_length=250, null=True)),
                ('bbb', models.CharField(blank=True, max_length=250, null=True)),
                ('ccc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contentsinfo',
            old_name='aaa',
            new_name='filesize',
        ),
        migrations.RemoveField(
            model_name='uploadcontents',
            name='totalpages',
        ),
    ]
