# Generated by Django 2.1.2 on 2019-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0004_auto_20190110_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcontents',
            name='is_delete',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
