# Generated by Django 2.1.5 on 2019-02-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0005_auto_20190212_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletinformation',
            name='contents_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unid.uploadContents'),
        ),
    ]
