# Generated by Django 2.1.2 on 2019-01-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0005_uploadcontents_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadcontents',
            old_name='is_delete',
            new_name='isdelete',
        ),
    ]
