# Generated by Django 2.1.2 on 2019-01-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0005_auto_20190129_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinions',
            old_name='aaa',
            new_name='exceptopinion',
        ),
    ]
