# Generated by Django 2.1.2 on 2019-01-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0006_auto_20190110_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcontents',
            name='previewpath',
        ),
    ]
