# Generated by Django 2.1.5 on 2019-02-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0006_walletinformation_contents_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletinformation',
            name='fromAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unid.myPageInfomation'),
        ),
    ]
