# Generated by Django 2.1.2 on 2019-01-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0006_auto_20190129_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='blackReasonForBan',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('aaa', models.CharField(blank=True, max_length=250, null=True)),
                ('bbb', models.CharField(blank=True, max_length=250, null=True)),
                ('ccc', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid.myPageInfomation')),
            ],
        ),
        migrations.CreateModel(
            name='unidBlackList',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('is_blacklist', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField()),
                ('aaa', models.CharField(blank=True, max_length=250, null=True)),
                ('bbb', models.CharField(blank=True, max_length=250, null=True)),
                ('ccc', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid.myPageInfomation')),
            ],
        ),
    ]
