# Generated by Django 2.1.2 on 2019-01-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0007_auto_20190130_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinions',
            old_name='bbb',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='opinions',
            old_name='ccc',
            new_name='type',
        ),
        migrations.AddField(
            model_name='opinions',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
