# Generated by Django 2.1.5 on 2019-02-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0007_walletinformation_fromaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletinformation',
            name='toAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toAccount', to='unid.myPageInfomation'),
        ),
        migrations.AlterField(
            model_name='walletinformation',
            name='fromAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromAccount', to='unid.myPageInfomation'),
        ),
    ]
