# Generated by Django 2.1.2 on 2019-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0007_remove_uploadcontents_previewpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previewinfo',
            old_name='ftpsavepreviewname',
            new_name='savepreviewname',
        ),
    ]
