# Generated by Django 2.1.2 on 2019-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0009_richtexttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richtexttest',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
