# Generated by Django 2.1.3 on 2019-02-13 18:17

import allauth.socialaccount.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0010_auto_20190213_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='unid.LikeUsers', to='unid.myPageInfomation'),
        ),
        migrations.AlterField(
            model_name='likeusers',
            name='liked_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid.myPageInfomation'),
        ),
        migrations.AlterField(
            model_name='richtexttest',
            name='delta_content',
            field=allauth.socialaccount.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='likeusers',
            unique_together={('liked_users', 'posts_id')},
        ),
    ]
