# Generated by Django 2.1.2 on 2019-02-15 14:11

import allauth.socialaccount.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0013_auto_20190215_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_path',
        ),
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=allauth.socialaccount.fields.JSONField(blank=True, null=True),
        ),
    ]
