# Generated by Django 2.1.2 on 2019-02-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0014_auto_20190215_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contents',
        ),
    ]
