# Generated by Django 2.1.2 on 2019-02-15 16:43

import allauth.socialaccount.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0015_remove_post_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents',
            field=allauth.socialaccount.fields.JSONField(blank=True, null=True),
        ),
    ]
