# Generated by Django 2.1.2 on 2019-02-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0016_post_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image_path', models.CharField(max_length=250)),
                ('background_image_path', models.CharField(max_length=250)),
                ('aaa', models.CharField(blank=True, max_length=250, null=True)),
                ('bbb', models.CharField(blank=True, max_length=250, null=True)),
                ('ccc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='aaa',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
