# Generated by Django 2.1.2 on 2019-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0017_auto_20190217_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundPost',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('context', models.CharField(max_length=250)),
                ('targetAmount', models.IntegerField()),
                ('currentAmount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('expireDate', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('funderEmail', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=250)),
                ('sharePeopleNumber', models.IntegerField()),
                ('aaa', models.CharField(blank=True, max_length=250, null=True)),
                ('bbb', models.CharField(blank=True, max_length=250, null=True)),
                ('ccc', models.CharField(blank=True, max_length=250, null=True)),
                ('ddd', models.CharField(blank=True, max_length=250, null=True)),
                ('eee', models.CharField(blank=True, max_length=250, null=True)),
                ('fff', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
