# Generated by Django 2.1.2 on 2019-02-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0018_fundpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpost',
            name='funderEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid.myPageInfomation'),
        ),
    ]
