# Generated by Django 2.1.2 on 2019-02-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0019_auto_20190218_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundpost',
            old_name='aaa',
            new_name='fundCategory',
        ),
        migrations.RenameField(
            model_name='fundpost',
            old_name='bbb',
            new_name='isfunding',
        ),
    ]
