# Generated by Django 2.1.3 on 2019-02-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0022_auto_20190218_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adbysuperuser',
            old_name='advertiser',
            new_name='adname',
        ),
        migrations.RenameField(
            model_name='advertise',
            old_name='background_image_path',
            new_name='advertiser',
        ),
        migrations.RenameField(
            model_name='advertise',
            old_name='title',
            new_name='company',
        ),
        migrations.AddField(
            model_name='adbysuperuser',
            name='ad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unid.advertise'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='enddate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advertise',
            name='introduce',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advertise',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advertise',
            name='startdate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
