# Generated by Django 2.1.3 on 2019-02-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0023_auto_20190221_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentsnouns',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('contents_nouns', models.CharField(blank=True, max_length=10000, null=True)),
                ('contents_id', models.CharField(blank=True, max_length=300, null=True)),
                ('aaa', models.CharField(blank=True, max_length=250, null=True)),
                ('bbb', models.CharField(blank=True, max_length=250, null=True)),
                ('ccc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
