# Generated by Django 2.1.2 on 2019-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0025_auto_20190222_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundpost',
            name='fff',
        ),
        migrations.AddField(
            model_name='fundpost',
            name='percent',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
