# Generated by Django 2.1.3 on 2019-02-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0026_auto_20190222_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundpost',
            old_name='fundaccount',
            new_name='ddd',
        ),
        migrations.RenameField(
            model_name='fundpost',
            old_name='txid',
            new_name='eee',
        ),
        migrations.RemoveField(
            model_name='fundpost',
            name='percent',
        ),
        migrations.AddField(
            model_name='fundpost',
            name='fff',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadcontents',
            name='checksimilar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
